import { OrderDataRepository, OrderFulfillmentDataRepository } from '../../infrastructure';
import { ListOrdersUseCase } from './ListOrders';
import { GetOrderUseCase } from './GetOrder';
import { GetCustomerOrdersUseCase } from './GetCustomerOrders';
import { UpdateOrderStatusUseCase } from './UpdateOrderStatus';
import { UpdatePaymentStatusUseCase } from './UpdatePaymentStatus';
import { UpdateFulfillmentStatusUseCase } from './UpdateFulfillmentStatus';
import { CancelOrderUseCase } from './CancelOrder';
import { ProcessRefundUseCase } from './ProcessRefund';
import { AddOrderNoteUseCase } from './AddOrderNote';
import { CreateOrderUseCase } from './CreateOrder';
import { CreateOrderRefundUseCase } from './CreateOrderRefund';
import { GetFulfillmentPackagesUseCase } from './GetFulfillmentPackages';
import { GetOrderDetailsUseCase } from './GetOrderDetails';
import { GetOrderRefundsUseCase } from './GetOrderRefunds';
import { GetOrdersByStoreUseCase } from './GetOrdersByStore';
import { ManageOrderFulfillmentsUseCase } from './ManageOrderFulfillments';
import { GetOrderForFulfillmentUseCase } from './GetOrderForFulfillment';
import { ManageOrderNotesUseCase } from './ManageOrderNotes';
import { ManageOrderItemsUseCase } from './ManageOrderItems';
import { GetOrderHistoryUseCase } from './GetOrderHistory';
import { ManageOrderReturnsUseCase } from './ManageOrderReturns';
import { ManageStorefrontReturnsUseCase } from './ManageStorefrontReturns';
import { TrackFulfillmentPackageUseCase } from './TrackFulfillmentPackage';

const orderRepo = OrderDataRepository.commands;
const orderQueryRepo = OrderDataRepository.queries;
const orderFulfillmentRepo = OrderFulfillmentDataRepository.fulfillments;
const orderReturnRepo = OrderFulfillmentDataRepository.returns;

export const listOrdersUseCase = new ListOrdersUseCase(orderRepo);
export const getOrderUseCase = new GetOrderUseCase(orderRepo);
export const getCustomerOrdersUseCase = new GetCustomerOrdersUseCase(orderRepo);
export const updateOrderStatusUseCase = new UpdateOrderStatusUseCase(orderRepo);
export const updatePaymentStatusUseCase = new UpdatePaymentStatusUseCase(orderRepo);
export const updateFulfillmentStatusUseCase = new UpdateFulfillmentStatusUseCase(orderRepo);
export const cancelOrderUseCase = new CancelOrderUseCase(orderRepo);
export const processRefundUseCase = new ProcessRefundUseCase(orderRepo);
export const addOrderNoteUseCase = new AddOrderNoteUseCase(orderRepo, orderQueryRepo);
export const createOrderUseCase = new CreateOrderUseCase(orderRepo);
export const createOrderRefundUseCase = new CreateOrderRefundUseCase(orderQueryRepo);
export const getFulfillmentPackagesUseCase = new GetFulfillmentPackagesUseCase(orderFulfillmentRepo);
export const getOrderDetailsUseCase = new GetOrderDetailsUseCase(orderRepo, orderQueryRepo);
export const getOrderRefundsUseCase = new GetOrderRefundsUseCase(orderQueryRepo);
export const getOrdersByStoreUseCase = new GetOrdersByStoreUseCase(orderRepo);
export const manageOrderFulfillmentsUseCase = new ManageOrderFulfillmentsUseCase(orderFulfillmentRepo, orderRepo);
export const getOrderForFulfillmentUseCase = new GetOrderForFulfillmentUseCase(orderRepo);
export const manageOrderNotesUseCase = new ManageOrderNotesUseCase(orderQueryRepo);
export const manageOrderItemsUseCase = new ManageOrderItemsUseCase(orderRepo);
export const getOrderHistoryUseCase = new GetOrderHistoryUseCase(orderRepo);
export const manageOrderReturnsUseCase = new ManageOrderReturnsUseCase(orderReturnRepo);
export const manageStorefrontReturnsUseCase = new ManageStorefrontReturnsUseCase(orderReturnRepo);
export const trackFulfillmentPackageUseCase = new TrackFulfillmentPackageUseCase(orderFulfillmentRepo);
import { GetStoreSalesSummaryUseCase } from './GetStoreSalesSummary';

export const getStoreSalesSummaryUseCase = new GetStoreSalesSummaryUseCase();
