/**
 * Generate the Docsify _sidebar.md by walking the docs/ directory.
 *
 * Produces a structured sidebar with sections for Guides, Architecture,
 * Modules, and Generated Reference.
 *
 * Usage: tsx scripts/docs/generate-sidebar.ts
 */

import fs from 'fs';
import path from 'path';

const DOCS_DIR = path.resolve(__dirname, '../../docs');
const OUTPUT = path.resolve(__dirname, '../../docs/_sidebar.md');

interface SidebarEntry {
  label: string;
  link: string;
}

interface SidebarSection {
  title: string;
  entries: SidebarEntry[];
}

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function scanDirectory(dir: string, prefix: string): SidebarEntry[] {
  const entries: SidebarEntry[] = [];
  const items = fs.readdirSync(dir, { withFileTypes: true });

  const files = items
    .filter(i => i.isFile() && i.name.endsWith('.md') && i.name !== 'README.md')
    .map(i => i.name)
    .sort();

  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    const label = titleCase(slug);
    const link = `${prefix}/${file}`.replace(/^\//, '');
    entries.push({ label, link });
  }

  return entries;
}

function main(): void {
  const sections: SidebarSection[] = [];

  // Guides
  const guidesDir = path.join(DOCS_DIR, 'guides');
  if (fs.existsSync(guidesDir)) {
    sections.push({
      title: 'Guides',
      entries: scanDirectory(guidesDir, '/guides'),
    });
  }

  // Architecture
  const archDir = path.join(DOCS_DIR, 'architecture');
  if (fs.existsSync(archDir)) {
    sections.push({
      title: 'Architecture',
      entries: scanDirectory(archDir, '/architecture'),
    });
  }

  // Guidelines
  const guidelinesDir = path.join(DOCS_DIR, 'guidelines');
  if (fs.existsSync(guidelinesDir)) {
    sections.push({
      title: 'Engineering Standards',
      entries: scanDirectory(guidelinesDir, '/guidelines'),
    });
  }

  // Modules
  const modulesDir = path.join(DOCS_DIR, 'modules');
  if (fs.existsSync(modulesDir)) {
    sections.push({
      title: 'Modules',
      entries: scanDirectory(modulesDir, '/modules'),
    });
  }

  // Generated
  const generatedDir = path.join(DOCS_DIR, 'generated');
  if (fs.existsSync(generatedDir)) {
    sections.push({
      title: 'Generated Reference',
      entries: scanDirectory(generatedDir, '/generated'),
    });
  }

  let md = '<!-- This file is auto-generated by `yarn docs:sidebar`. Do not edit manually. -->\n\n';

  for (const section of sections) {
    md += `- **${section.title}**\n`;
    for (const entry of section.entries) {
      md += `  - [${entry.label}](${entry.link})\n`;
    }
    md += '\n';
  }

  fs.writeFileSync(OUTPUT, md);
  const total = sections.reduce((sum, s) => sum + s.entries.length, 0);
  console.log(`[docs:sidebar] Generated ${OUTPUT} (${total} entries in ${sections.length} sections)`);
}

main();
